packages:
  - "call-ai/pkg"
  - "call-ai/tests/unit"
  - "call-ai/tests/integration"
  - "use-vibes/types"
  - "use-vibes/base"
  - "use-vibes/pkg"
  - "use-vibes/tests"
  - "use-vibes/examples/react-example"
  - "vibes.diy/pkg"
  - "vibes.diy/tests/app"
  - "vibes.diy/tests/simple-chat"
  - "prompts/pkg"
  - "prompts/tests"

# Avoid needing to interactively run 'pnpm approve-build' step during quickstart
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "core-js"
  - "es5-ext"
  - "esbuild"
  - "netlify"
  - "netlify-cli"
  - "playwright-chromium"
  - "sharp"
  - "unix-dgram"
  - "unrs-resolver"
  - "workerd"
